language: python
python:
    - "3.5"
    - "3.4"
install:
    - make build
    - pip install codecov
script:
    - flake8
    - python -m unittest tests/test_service.py
    - coverage run -m unittest tests/*.py
after_success:
    - codecov
